apiVersion: v1
data:
  token: ZXlKaElqb2lNVFl5Wm1VMVpqSXdNamRoTnpBNE56TmpZbU0wWlRnMU9UTTJZakJqT1RZaUxDSjBJam9pTldNeE9USTBaVE10TVRRNU15MDBNR0l5TFRsaFl6TXRZbVJoTURabVpUY3dZVFJoSWl3aWN5STZJbGw2U21oUFYwcHJUbnBaZEZwdFJUSk5lVEF3V1hwSk1FeFhSbXhaYlVWMFdWZFpNMDFxUW0xT2FrNW9UMVJvYkNKOQ==
kind: Secret
metadata:
  name: cloudflare-token
  namespace: default
